### ISSUE TITLE
Clicking links in output window results in 'File not found'

### ISSUE THREAD

**Issue by vslotman** [raycarter/tcl-outline-vscode#4]
When I have the following output:
SomeCommand { arg }  -- file:///path/to/file.inc:123

Ctrl-clicking the link results in the following error-message:
Unable to open 'file.inc:123': File not found (/path/to/file.inc:123).
Looks like the line-number is not correctly stripped from the link.

I'm using the following versions:
VS Code: 1.10.2 
tcl-outline: 0.1.2

**Comment by raycarter** [comment]
i will try to fix it when i have some time. thanks for your issue report!
